### ISSUE TITLE
repeatable results?

### ISSUE THREAD

**Issue by Fil** [Kcnarf/d3-voronoi-map#2]
I don't think there is any random element in the following observable
https://beta.observablehq.com/@fil/voronoi-weighted-maps
yet the results vary between runs.

**Comment by michaschwab** [comment]
See https://github.com/Kcnarf/d3-voronoi-treemap/issues/4.

I'm working on a pull request to fix this.

**Comment by Kcnarf** [comment]
@fil: I see you use the 'pie' initial position, which actually removes the randomness at initilization. It works fine when there is *no too much data*. In your use case, it doesn't produce the same arrangement because during the iterative process producing the final arrangement, some of your data (the lightest) are completely overweighted (they are too close to other heavier cells, and they are assigned an empty area). In such a case, the algorithm randomly choose a new position where such cell still exists. This is why you get different Voronoï maps when reloading.

The PR from @michaschwab is the solution: re-positioning of overweighted cells will become repeatable. It is orthogonal to the 'pie' initial positioning, and both codes will perfectly work together. Nevertheless, the doc of the 'pie' initial positioning have to be updated.

I will not be able to work on @michaschwab's PR before next week (from 13th aug. 2018).

**Comment by Kcnarf** [comment]
After some googling, I found another way to make a repeatable Voronoï map with the help of  [seedrandom](https://github.com/davidbau/seedrandom).

As the @michaschwab's PR does, it defines a PRNG. It may be used to replace/overwrite `Math.random()`. You can see it in action in https://beta.observablehq.com/@kcnarf/repeatable-voronoi-weighted-maps (focus on https://beta.observablehq.com/@kcnarf/repeatable-voronoi-weighted-maps#voronoiMap). Indeed, the initial 'pie' positioning is no longer required for the sake of repeatability.

Seedrandom can also be used without overwriting `Math.random()`, and without introducing any side effect, by defining a new standalone PRNG. Enhancing d3-voronoi-map by providing an API that allows the user to set its preferred random generator (see [d3-random](https://github.com/d3/d3-random)) is another implementation that allows repeatable Voronoï map.

**Comment by Kcnarf** [comment]
The new version 1.2.0 of the d3-voronoi-map plugin now provides a new 'prng' API. It allows to define a prng. If this one is _seeded_, then randomness becomes repeatable, leading to repeatable outputs/arrangements.

You can see it in action in https://beta.observablehq.com/@kcnarf/repeatable-voronoi-weighted-maps (focus on https://beta.observablehq.com/@kcnarf/repeatable-voronoi-weighted-maps#voronoiMap). Indeed, the initial 'pie' positioning is no longer required for the sake of repeatability.
