### ISSUE TITLE
Deterministic Layout 

### ISSUE THREAD

**Issue by susielu** [Kcnarf/d3-voronoi-map#4]
Thanks for this great library @Kcnarf ! Really enjoying exploring data with this lib and the `d3-voronoi-treemap`. I want to be able to create a deterministic layout so if I send the same data and parameters it always creates the same layout voronoi. What is the best way to achieve this?

**Comment by susielu** [comment]
OH  just found your block on using [initialPosition](http://bl.ocks.org/Kcnarf/e649c8723eff3fd64a23f75901910930) very helpful. Closing this, thanks!

**Comment by Kcnarf** [comment]
Hi susie,
I'm very pleased you use these plugins, and also that you find these useful.

Regarding your question about deterministic layout, I think there is two ways to do it:
1. the easy way: use the [prng()](https://github.com/Kcnarf/d3-voronoi-map#simulation_prng) API so that you alway have the same final layout; but you haven't any kind of control over this final layout
1. the hard way: use the [intial position](https://github.com/Kcnarf/d3-voronoi-map#simulation_initialPosition) API so that you control the first position of seeds, and thus control _more or less_ the final layout

For the hard way, I say _'more or less'_ because the algorithm may fall in a situation where a seed must be randomly re-positioned (in case the seed is overweighted by other seeds and has no area left, re-positioning allows to retrieve an area). It is not an issue, except I will recommand to define a prng() in addition to the intialPosition(), so that you will have a repeatable final layout.

I hope I'm clear enough.
